### ISSUE TITLE
Multiple entries for component in `bower.json` main for `.html` file type

### ISSUE THREAD

**Issue by peterblazejewicz** [PolymerElements/paper-icon-button#89]
This commit:
https://github.com/PolymerElements/paper-icon-button/commit/95bde452267de3a5e0a0f6e34c997ed5c4d7b2f5
added `light` version of component - at the same time duplicating entry in `bower.json` main field:
https://github.com/PolymerElements/paper-icon-button/blame/master/bower.json#L7-L10

The specs recommends only single entry per file type:
https://github.com/bower/spec/blob/master/json.md#main
So this is not an error, but a warning:
```
bower paper-icon-button#* invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["paper-icon-button.html","paper-icon-button-light.html"]
```
Still marked as `invalid-meta` for end users.
Thanks!

**Comment by notwaldorf** [comment]
Unfortunately, we are using those multiple entries in the `main` field as metadata so that both elements show up in the [catalog](https://elements.polymer-project.org/elements/paper-icon-button) docs. So even though it's annoying as a warning, I don't think this is something that we can fix right now :(

/cc @azakus @justinfagnani
