### ISSUE TITLE
The docs say that a default icon set is included with this element, but no icon set is.

### ISSUE THREAD

**Issue by akc42** [PolymerElements/paper-icon-button#98]
The documents says this element includes a "default set" of icons.  But it doesn't include any icons, you have to import them separately to make the icon show up.

**Comment by vvaradarajan** [comment]
The import icon statement is there in paper-icon-button.html. 
<link rel="import" href="../iron-icon/iron-icon.html">
However this iron-icon.html does not work
Changing this to <link rel="import" href="../iron-icons/iron-icons.html"> along with bower install of iron-icons works.
My guess is to either correct this or remove the import and  update the documentation to indicate explicit inclusion of icon file.

**Comment by notwaldorf** [comment]
Oh, hmm, yeah I think the docs are wrong and should probably be updated. You need to also install `iron-icons` for this to work.

**Comment by vvaradarajan** [comment]
The paper-icon-button.html on GitHub can be modified to import the
'iron-icons' instead of 'iron-icon'.


On May 9, 2017 1:43 AM, "Monica Dinculescu" <notifications@github.com>
wrote:

Oh, hmm, yeah I think the docs are wrong and should probably be updated.
You need to also install iron-icons for this to work.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PolymerElements/paper-icon-button/issues/98#issuecomment-300100264>,
or mute the thread

**Comment by notwaldorf** [comment]
That would not be correct. Paper-icon-button has a hard dependency on iron-icon (which actually renders the icon), but only a dev dependency on iron-icons (so that it's used in the demo). Making that a hard dependency means everyone who wants to use a paper-icon-button would *have* to download the default set of icons, whether or or not they would use it, which is bad (and expensive)

**Comment by vvaradarajan** [comment]
Thx for the clarification.  I did not know that iron-icon had the rendering
portion. I have both iron-icon and iron-icons installed, and when the
default paper-icon-button did not display the icon, I changed the
paper-icon-button.html to replace iron-icon with iron-icons, and that
worked.
Now I understand that iron-icons includes the rendering portion AND icons,
whereas iron-icon probably has the rendering portion.
Thx for reading/responding to my emails.

-Vasan

On Tue, May 9, 2017 at 10:54 AM, Monica Dinculescu <notifications@github.com
